language: node_js
node_js:
    - "lts/*"

addons:
    firefox: "latest"

env:
    global:
    # Codacy credentials for code coverage
    - secure: "lv5xQ9kkkqUsW08xN81yQbJXdqOO+dTjuMjCAw4DjIz2tRcfstDXHNqLpasuLP8EbBxRjYcfgWV2+6/FGeDsZKQtHtSOQdROELTBu1YPtCTJL2wm4iYKqZKBpHBxPwRhlfqfw6ry7cplyn7j33RtrzO31wDKCJ81BW9KCqAunqKfJNZfF/cehVYdv8na+5U+YHTO30yfgnb/rABjhOKhHdxCANBfopqgAARQE9mXnp7MCQ3QZPRoH9YcLKBX7hojT8Qlk7IgU+vWBFyAijr1Q6PMNunsuLPtv/5UIRhNirr70HsJ8qDtF4WkGii3BpNBpwBolkEbUEWuenHbzEYxyVWc+bNtzb3+MaJKGjnLmDAB3V1zmQe6X4kxuZcPqESF4vnD7uQHXSmvtR3MAKfrh6XmckwMcBhstVArSU6m5SnAmBIOOyIUSTcQ3usOoNOqEh0J9MkF5SXO+DDJIDlB6mYvf/6Qev4x6CoLfkCnOxmhdM+MD+hSbusbVpLwK3ohIL//cBkmoVr38mE3pZR0izwxRPMFYJlh3nvRPzpJi+jcpsQvsm7T6xfq/+xVKEwG8NTfMBKrUQcvWKc3mRzDRTuM6GckkKIe0F3dySnRa4aBD0j3opBHrC30VtMX37Cj5pdqSaWxDYmyF2kVtLhDDFQlHXiKNLGFgeiNUw4n4CE="

before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

script:
    - npm test
    - codacy-coverage coverage/F*/lcov.info

